name: agora_video_chat_flutter
description: A Flutter project for video calls and text chat using Agora.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Agora RTC Engine per video chiamate
  agora_rtc_engine: ^6.3.2

  # Agora Chat SDK per chat testuale
  agora_chat_sdk: ^1.3.1

  flutter_chat_ui: ^2.0.0

  agora_uikit: ^1.3.1


  # HTTP client per chiamate API
  http: ^1.1.0

  # State management
  provider: ^6.1.1

  # UUID generator
  uuid: ^4.2.1

  # Routing
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
